# Meta Data for SEO

## Homepage
title = "fullstackhero"
titleSeparator = "-"
titleAddition = "Open-Source Framework for Modern Web Applications."
description = "fullstackhero is an ambitious project to cater the needs of Developers and Organizations and helps reduce the development hours by over 200+ hours!"
logo = "/images/full-stack-hero-logo.png"
navBarLogo = "/images/navbar-logo.png"

## Documentation
# docsVersion = "1"

# Search
mainSections = ["blog", "blazor-webassembly-boilerplate", "dotnet-webapi-boilerplate", "basics"]

## Open Graph
images = ["fullstackhero.png"]
ogLocale = "en_US"
domainTLD = "doks.netlify.app"
titleHome = "Doks Theme"

## Twitter Cards
twitterSite = "@codewithmukesh"
twitterCreator = "@iammukeshm"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "fullstackhero"
schemaAuthor = "Mukesh Murugan"
schemaAuthorTwitter = "https://twitter.com/iammukeshm"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/iammukeshm/"
schemaAuthorGitHub = "https://github.com/iammukeshm"
schemaLocale = "en-US"
schemaLogo = "logo-fullstackhero.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "fullstackhero.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/codewithmukesh"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/fullstackhero"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 100
bgColor = "#fff"
landscapePhotoWidths = [2000, 1000, 900, 800, 700, 600, 500,400]
portraitPhotoWidths = [800, 700, 600, 500,100]
lqipWidth = "20x"
smallLimit = "30"

# Footer
footer = "Developed & Maintained by <a href=\"https://www.codewithmukesh.com/\">Mukesh Murugan</a>"

# Feed
copyRight = "Copyright (c) 2021-2022 Mukesh Murugan"

# Alert
alert = true
alertDismissable = false
alertText = ".NET 7 WebAPI Boilerplate Released 🚀😁 <a target=\"_blank\" class=\"alert-link\" href=\"https://www.youtube.com/watch?v=a1mWRLQf9hY&ab_channel=MukeshMurugan/\">Click here to get started! 😎☕</a>"

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/fullstackhero/docs"
docsRepoBranch = "master"
editPage = true
lastMod = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = false
